# Generated by Django 5.0.6 on 2024-06-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="is_complete",
            new_name="is_completed",
        ),
    ]
